version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: apsicologia-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: apsicologia
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - apsicologia-network

  # Redis Cache & Sessions
  redis:
    image: redis:7-alpine
    container_name: apsicologia-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redispassword123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - apsicologia-network

  # MinIO S3 Compatible Storage
  minio:
    image: minio/minio:latest
    container_name: apsicologia-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - apsicologia-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mongodb_data:
  redis_data:
  minio_data:

networks:
  apsicologia-network:
    driver: bridge