packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # Core dependencies
  typescript: ^5.3.0
  zod: ^3.22.0
  date-fns: ^2.30.0
  date-fns-tz: ^2.0.0
  
  # Dev dependencies
  '@types/node': ^20.10.0
  eslint: ^8.55.0
  prettier: ^3.1.0
  jest: ^29.7.0
  '@types/jest': ^29.5.0
  vitest: ^1.0.0
